###
POST http://localhost:7878/api/user HTTP/1.1
content-type: application/json

{
    "first_name": "Jordan",
    "last_name": "Samson",
    "user_name": "jsamson",
    "email": "jkdsamson@outlook.com",
    "phone": "0452339108",
    "password": "Jojo the 123!"
}

###
POST http://localhost:7878/api/user/login HTTP/1.1
content-type: application/json

{
    "user_name": "johndoe",
    "password" : "password123"
}

###
GET http://localhost:7878/api/health-check/check HTTP/1.1

###
GET http://localhost:7878/api/world-aths/read HTTP/1.1

###
GET http://localhost:7878/api/system/cpu HTTP/1.1

###
GET http://localhost:7878/api/system/details HTTP/1.1

###
GET http://localhost:7878/api/world-aths/points/Outdoor/Male/200m?mark=21.98 HTTP/1.1

###
GET http://localhost:7878/api/world-aths/points/Outdoor/Male/100m?mark=10.44 HTTP/1.1



# ###Default
# GET http://localhost:7878/pages/points HTTP/1.1
# ###
# GET http://localhost:7878/pages/points/Outdoor/Male/100m?mark=10.44 HTTP/1.1